# 2. main.yml
---
- name: Arch Linux Configuration
  hosts: localhost
  become: yes

  roles:
    - role: initial_install
    - role: password_manager_setup
    - role: ssh_setup
    - role: hyprdots_installation
    - role: backup_creation
