# 3. roles/password_manager_setup/tasks/main.yml
---
- name: Install pass and gnupg
  pacman:
    name: 
      - pass
      - gnupg
    state: present

- name: Generate GPG key
  command: >
    gpg --batch --gen-key <<EOF
    Key-Type: {{ gpg_key_type }}
    Key-Length: {{ gpg_key_length }}
    Subkey-Type: {{ gpg_subkey_type }}
    Subkey-Length: {{ gpg_subkey_length }}
    Name-Real: {{ user_name }}
    Name-Email: {{ user_email }}
    Expire-Date: {{ gpg_expire_date }}
    %commit
    EOF
  args:
    creates: ~/.gnupg/pubring.kbx

- name: Initialize pass
  command: pass init "{{ user_email }}"
  args:
    creates: ~/.password-store/.gpg-id